### ISSUE TITLE
feature: Command specification without implied shell

### ISSUE THREAD

**Issue by Mange** [Mange/tydra#11]
It would be great to be able to run a command in a way that makes it possible to run a executable directly without running it as a process inside a `/bin/sh` shell.

This is also very useful if a script is to generate the tydra specification dynamically as there is no need to escape strings or worry about word splitting or shell globs.

**Proposed solution:**

```yaml
title: Show home files
shell: "ls ~"

# Equivalent to
title: Show home files
command:
  name: sh
  args:
    - "-c"
    - "ls ~"
```

```yaml
# Not possible right now without manually escaping
title: Show the file named *
command:
  name: ls
  args:
    - "-l"
    - "*"
```
