### ISSUE TITLE
feature: Command output modes

### ISSUE THREAD

**Issue by Mange** [Mange/tydra#8]
From experience, I have some common patterns that could be extracted into some sort of "command output mode" setting so it does not have to be repeated all over.

- Render output without previous history visible.
  - Switching away from alternate screen shows all previous history, and retains this history when tydra exits. Sometimes you want a clean output.
- Disregard output (#1).
- Paging output.

```yaml
output: ignore # return immediately without any output; use null devices as stdin/out/err to process.
output: keep # current behavior; render outside of the alternate screen
output: dedicated # render on a new clean screen instead of on the normal screen
output: paged # pipe to $PAGER / less
```

`dedicated` seems like a good default.
